#Docker image to run the pipeline
default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init
  cache:
    key: terraform
    paths:
      - .terraform

#Defining the structure of the pipeline
stages:
  - stg_validate
  - stg_plan
  - stg_apply
  - stg_destroy
 
 #Defining the jobs that will run in each stage
 gtt-tf-validate:
  stage: stg_validate
  script:
    - echo "Validating terraform code..."
    - terraform validate
  except:
    refs:
      -master
  
 gtt-tf-plan:
  stage: stg_plan
  script: 
 
 gtt-tf-apply:
  stage: stg_apply
 
 gtt-tf-destroy:
  stage: stg_destroy
  
